apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-next-app-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: my-next-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: my-next-app
    spec:
      containers:
        - name: my-next-app
          image: ${DOCKER_REGISTRY}/my-next-app:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 
        imagePullSecrets:
          - name: myregistrykey


---

apiVersion: v1 
kind: Service 
metadata: 
  name: my-next-app-svc
  namespace: webapps
spec:
  selector:
    app: my-next-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer 